basePath: /v2
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: kkkkkkkkkkk
    url: http://www.swagger.io/support
  description: kkkkkkkkkkkke server Petstore server.
  license:
    name: kkkk
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: aaaaaaaaaaaaaaaaa
  version: "1.0"
paths: {}
swagger: "2.0"
